In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# data gán nhãn thứ 1
df1 = pd.read_csv('/content/drive/MyDrive/DS310/datasetNLP/dataset2.7_1.csv')

In [ ]:
# data gán nhãn thứ 2
df2 = pd.read_csv('/content/drive/MyDrive/DS310/datasetNLP/dataset2.7_2.csv')

In [ ]:
df1[['Service', 'Infrastructure', 'Sanitary', 'Location', 'Attitude']].head(5)

   Service  Infrastructure  Sanitary  Location  Attitude
0      0.0             0.0       0.0       0.0       2.0
1      1.0             0.0       0.0       0.0       2.0
2      0.0             0.0       0.0       0.0       2.0
3      1.0             1.0       0.0       1.0       1.0
4      0.0             0.0       0.0       0.0       2.0

So sánh 2 bộ data, tìm số lượng và vị trí các giá trị không không nhau của 2 bộ data đã gán nhãn

In [ ]:
df_temp = df1[['Attitude']][0:2231] != df2[['Attitude']][0:2231]
df_temp = df_temp[df_temp['Attitude'] == True]
df_temp['Index'] = df_temp.index + 2
df_temp['Comment'] = df1.Comment[df_temp.index]
#df_temp.to_csv('df_att.csv', index=False, header=True)

In [ ]:
df_temp

      Attitude  Index                                            Comment
15        True     17  Phòng ốc rất ok so với giá nhưng nhà vệ sinh k...
18        True     20  Oceanami biệt_thự Có vị trí thuận tiện, khuôn ...
20        True     22  Hình ảnh phòng trên web chỉ mang tính chất min...
30        True     32                          Tốt. Không có gì phàn nàn
36        True     38  Bãi biển có bể bơi nước ấm vào mùa đông nên nh...
...        ...    ...                                                ...
2126      True   2128  nhân_viên của khu_nghỉ_mát thân thiện, phục_vụ...
2129      True   2131  nhân_viên tư vấn: hỗ trợ. \n\ndịch_vụ khách_sạ...
2201      True   2203                    Trang thiết bị cũ kỹ. Phòng ẩm.
2209      True   2211  dịch_vụ khách_sạn tốt, tôi hoàn toàn không phà...
2210      True   2212  Phòng và dịch_vụ rất tốt, tuy nhiên buffet sán...

[160 rows x 3 columns]

In [ ]:
df_temp = df1[['Service']][0:2231] != df2[['Service']][0:2231]
df_temp = df_temp[df_temp['Service'] == True]
df_temp['Index'] = df_temp.index + 2
df_temp['Comment'] = df1.Comment[df_temp.index]
#df_temp.to_csv('df_ser.csv', index=False, header=True)

In [ ]:
df_temp

      Service  Index                                            Comment
18       True     20  Oceanami biệt_thự Có vị trí thuận tiện, khuôn ...
25       True     27  Rất tốt, chuyến đi gia đình tôi rất hài lòng. ...
27       True     29  Khi Tôi đi Tôi có phát sinh 2 bé dưới 5 tuổi v...
30       True     32                          Tốt. Không có gì phàn nàn
39       True     41  Phòng sạch_sẽ, tinh tế từ những chi tiết nhỏ. ...
...       ...    ...                                                ...
1793     True   1795  Phòng khá ổn cho đôi mới cưới đi tuần trăng mậ...
1984     True   1986  Nội thất khách_sạn cũ, phòng không giống với q...
2117     True   2119  Khi nhận phòng tại đây chúng tôi phải chuyển p...
2197     True   2199  khách_sạn rất là tốt luôn. đặt qua ivivu phản ...
2215     True   2217  khu_nghỉ_mát đẹp, xanh mát. Đồ ăn sáng buffet ...

[93 rows x 3 columns]

In [ ]:
df_temp = df1[['Infrastructure']][0:2231] != df2[['Infrastructure']][0:2231]
df_temp = df_temp[df_temp['Infrastructure'] == True]
df_temp['Index'] = df_temp.index + 2
df_temp['Comment'] = df1.Comment[df_temp.index]
#df_temp.to_csv('df_inf.csv', index=False, header=True)

In [ ]:
df_temp

      Infrastructure  Index                                            Comment
33              True     35  khách_sạn không phục_vụ buffet ăn, mà chỉ có c...
35              True     37  Khu nghỉ dưỡng tuyệt vời, cảnh đẹp, chụp hình ...
39              True     41  Phòng sạch_sẽ, tinh tế từ những chi tiết nhỏ. ...
47              True     49  dịch_vụ tốt, do đang sửa chữa nên hơi ồn, nhân...
50              True     52                                          tuyệt vời
...              ...    ...                                                ...
2072            True   2074  Lần thứ 2 ở Rex. Săn được đơn tốt nên giá siêu...
2210            True   2212  Phòng và dịch_vụ rất tốt, tuy nhiên buffet sán...
2214            True   2216  tốt. Tôi rất thích khách_sạn cũng như các comb...
2227            True   2229  Đồ ăn sáng không ngon, phòng có mùi khó chịu v...
2230            True   2232  Tôi rất hài lòng về dịch_vụ khách_sạn này, với...

[171 rows x 3 columns]

In [ ]:
df_temp = df1[['Sanitary']][0:2231] != df2[['Sanitary']][0:2231]
df_temp = df_temp[df_temp['Sanitary'] == True]
df_temp['Index'] = df_temp.index + 2
df_temp['Comment'] = df1.Comment[df_temp.index]
#df_temp.to_csv('df_san.csv', index=False, header=True)

In [ ]:
df_temp

      Sanitary  Index                                            Comment
50        True     52                                          tuyệt vời
51        True     53  Phòng cách âm tệ, quá ồn không nghỉ ngơi được,...
60        True     62  Mọi thứ tôi thấy hầu  như đều tốt. Chuyến đi t...
62        True     64           khách_sạn mới...mọi thứ ổn.hồ bơi đẹp...
64        True     66  khách_sạn sạch_sẽ, nhân_viên dễ thương, vị trí...
...        ...    ...                                                ...
1727      True   1729  Hành lang và phòng ngủ tối u ám không được sán...
1900      True   1902  Phòng phù hợp, bữa sáng chu đáo hợp khẩu vị. B...
2194      True   2196  khách_sạn sạch_sẽ, đầy đủ tiện nghi. giá_cả hợ...
2203      True   2205  Phòng khung_cảnh biển ok, sạch, nội thất đẹp, ...
2205      True   2207  Lễ tân, cô dọn phòng siêu dễ thương, phòng ổn ...

[161 rows x 3 columns]

In [ ]:
df_temp = df1[['Location']][0:2231] != df2[['Location']][0:2231]
df_temp = df_temp[df_temp['Location'] == True]
df_temp['Index'] = df_temp.index + 2
df_temp['Comment'] = df1.Comment[df_temp.index]
#df_temp.to_csv('df_loc.csv', index=False, header=True)

In [ ]:
df_temp

      Location  Index                                            Comment
62        True     64           khách_sạn mới...mọi thứ ổn.hồ bơi đẹp...
72        True     74                                                 Ok
79        True     81  Tôi thấy khách_sạn có chất lượng tương xứng vớ...
82        True     84  dịch_vụ tốt. Bãi biển buổi sáng nước trong veo...
86        True     88  phục_vụ tốt nhưng do chuyến đi tôi do bão nên ...
...        ...    ...                                                ...
2162      True   2164  Thật sự rất đáng để trải nghiệm khu_nghỉ_mát y...
2180      True   2182  Nơi tốt, dịch_vụ và địa điểm cho chuyến đi ngắ...
2194      True   2196  khách_sạn sạch_sẽ, đầy đủ tiện nghi. giá_cả hợ...
2213      True   2215  Phòng đẹp, trang trí nội thất kiểu sang trọng,...
2219      True   2221  nhân_viên Nguyễn Trọng Đức tư vấn rất tốt !!\n...

[84 rows x 3 columns]